#name, main, version and api are required
name: PureEntities
main: VorgeRyan\pureentities\PureEntities
#remember version and api is string, don't write it like this: 1.0.0, or there will be an exception
version: "1.0"
api: ["2.0.0", "1.14.0"]

load: STARTUP
author: VorgeRyan
description: Implement all MCPE entities
commands: []